# Generated by Django 4.1.2 on 2022-11-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Консоль',
                'verbose_name_plural': 'Консоли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, unique=True, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Локализация',
                'verbose_name_plural': 'Локализации',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('release_date', models.DateField(null=True, verbose_name='Дата выхода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meappe.category', verbose_name='Категория')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meappe.console', verbose_name='Консоль')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meappe.genre', verbose_name='Жанр')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meappe.localization', verbose_name='Локализация')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meappe.console', verbose_name='Консоль'),
        ),
    ]
