# Generated by Django 4.1.2 on 2022-11-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0002_alter_product_options_remove_category_console_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meappe.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meappe.console', verbose_name='Консоль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meappe.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meappe.localization', verbose_name='Локализация'),
        ),
    ]
