# Generated by Django 4.1.2 on 2022-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0003_alter_product_category_alter_product_console_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='console',
        ),
        migrations.AddField(
            model_name='product',
            name='console',
            field=models.ManyToManyField(blank=True, related_name='products', to='meappe.console', verbose_name='Консоль'),
        ),
    ]
