# Generated by Django 4.1.2 on 2022-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0004_remove_product_console_product_console'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='console',
            field=models.ManyToManyField(blank=True, related_name='products', to='meappe.console', verbose_name='Консоли'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='localization',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='products', to='meappe.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='product',
            name='localization',
            field=models.ManyToManyField(blank=True, related_name='products', to='meappe.localization', verbose_name='Локализация'),
        ),
    ]
