# Generated by Django 4.1.2 on 2022-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0005_alter_product_console_remove_product_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=300, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
