# Generated by Django 4.1.2 on 2022-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0006_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='nnn', max_length=300, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
