# Generated by Django 4.1.2 on 2022-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icons/categories', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='console',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icons/consoles', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='genre',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icons/genres', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='localization',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='icons/localizations', verbose_name='Иконка'),
        ),
    ]
