# Generated by Django 4.1.2 on 2022-11-19 18:59

from django.db import migrations, models
import django.db.models.deletion
import meappe.models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0009_remove_localization_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=meappe.models.img_path, verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meappe.product')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='meappe.image', verbose_name='Фото'),
        ),
    ]
