# Generated by Django 4.1.2 on 2022-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0010_remove_product_img_image_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='products', to='meappe.image', verbose_name='Фото'),
        ),
    ]
