# Generated by Django 4.1.2 on 2022-12-03 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0015_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='URL'),
        ),
    ]
