# Generated by Django 4.1.2 on 2022-12-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meappe', '0018_order_alter_image_product_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('Подтвержден', 'Подтвержден'), ('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен')], default='Оформлен', max_length=300, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
